[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.pyi?$"

[tool.ruff]
line-length = 100
target-version = "py311"
select = [
  "E",
  "F",
  "B",
  "UP",
  "S",
  "RUF",
]
ignore = ["E501"]
fix = true

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.mypy]
python_version = "3.11"
plugins = []
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
follow_imports = "silent"
strict_optional = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
show_error_codes = true
ignore_missing_imports = true
