"""add_more_missing_columns_to_candidates

Revision ID: 3c20e838905b
Revises: 7b5286821f25
Create Date: 2025-10-19 02:35:06.737278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c20e838905b'
down_revision: Union[str, None] = '7b5286821f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the missing columns to candidates table
    op.add_column('candidates', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('current_address', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('address_banchi', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('address_building', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('building_name', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('registered_address', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('passport_number', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('passport_expiry', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('residence_status', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('residence_expiry', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('license_expiry', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('car_ownership', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('voluntary_insurance', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('forklift_license', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('tama_kake', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('mobile_crane_under_5t', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('mobile_crane_over_5t', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('gas_welding', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('family_name_1', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('family_relation_1', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_age_1', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('family_residence_1', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_separate_address_1', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('family_name_2', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('family_relation_2', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_age_2', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('family_residence_2', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_separate_address_2', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('family_name_3', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('family_relation_3', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_age_3', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('family_residence_3', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_separate_address_3', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('family_name_4', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('family_relation_4', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_age_4', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('family_residence_4', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_separate_address_4', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('family_name_5', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('family_relation_5', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_age_5', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('family_residence_5', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('family_separate_address_5', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('work_history_company_7', sa.String(length=200), nullable=True))
    op.add_column('candidates', sa.Column('work_history_entry_company_7', sa.String(length=200), nullable=True))
    op.add_column('candidates', sa.Column('work_history_exit_company_7', sa.String(length=200), nullable=True))
    op.add_column('candidates', sa.Column('exp_nc_lathe', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_lathe', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_press', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_forklift', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_packing', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_welding', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_car_assembly', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_car_line', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_car_inspection', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_electronic_inspection', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_food_processing', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_casting', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_line_leader', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_painting', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('exp_other', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('bento_lunch_dinner', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('bento_lunch_only', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('bento_dinner_only', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('bento_bring_own', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('commute_method', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('commute_time_oneway', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('interview_result', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('antigen_test_kit', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('antigen_test_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('covid_vaccine_status', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('language_skill_exists', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('language_skill_1', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('language_skill_2', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('japanese_qualification', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('jlpt_taken', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('jlpt_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('jlpt_score', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('jlpt_scheduled', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('qualification_1', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('qualification_2', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('qualification_3', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('major', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('blood_type', sa.String(length=5), nullable=True))
    op.add_column('candidates', sa.Column('dominant_hand', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('allergy_exists', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('listening_level', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('speaking_level', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('safety_shoes', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('read_katakana', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('read_hiragana', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('read_kanji', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('write_katakana', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('write_hiragana', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('write_kanji', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('can_speak', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('can_understand', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('can_read_kana', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('can_write_kana', sa.String(length=20), nullable=True))


def downgrade() -> None:
    # Remove the columns
    op.drop_column('candidates', 'can_write_kana')
    op.drop_column('candidates', 'can_read_kana')
    op.drop_column('candidates', 'can_understand')
    op.drop_column('candidates', 'can_speak')
    op.drop_column('candidates', 'write_kanji')
    op.drop_column('candidates', 'write_hiragana')
    op.drop_column('candidates', 'write_katakana')
    op.drop_column('candidates', 'read_kanji')
    op.drop_column('candidates', 'read_hiragana')
    op.drop_column('candidates', 'read_katakana')
    op.drop_column('candidates', 'safety_shoes')
    op.drop_column('candidates', 'emergency_contact_phone')
    op.drop_column('candidates', 'emergency_contact_relation')
    op.drop_column('candidates', 'emergency_contact_name')
    op.drop_column('candidates', 'speaking_level')
    op.drop_column('candidates', 'listening_level')
    op.drop_column('candidates', 'allergy_exists')
    op.drop_column('candidates', 'dominant_hand')
    op.drop_column('candidates', 'blood_type')
    op.drop_column('candidates', 'major')
    op.drop_column('candidates', 'qualification_3')
    op.drop_column('candidates', 'qualification_2')
    op.drop_column('candidates', 'qualification_1')
    op.drop_column('candidates', 'jlpt_scheduled')
    op.drop_column('candidates', 'jlpt_score')
    op.drop_column('candidates', 'jlpt_date')
    op.drop_column('candidates', 'jlpt_taken')
    op.drop_column('candidates', 'japanese_qualification')
    op.drop_column('candidates', 'language_skill_2')
    op.drop_column('candidates', 'language_skill_1')
    op.drop_column('candidates', 'language_skill_exists')
    op.drop_column('candidates', 'covid_vaccine_status')
    op.drop_column('candidates', 'antigen_test_date')
    op.drop_column('candidates', 'antigen_test_kit')
    op.drop_column('candidates', 'interview_result')
    op.drop_column('candidates', 'commute_time_oneway')
    op.drop_column('candidates', 'commute_method')
    op.drop_column('candidates', 'bento_bring_own')
    op.drop_column('candidates', 'bento_dinner_only')
    op.drop_column('candidates', 'bento_lunch_only')
    op.drop_column('candidates', 'bento_lunch_dinner')
    op.drop_column('candidates', 'exp_other')
    op.drop_column('candidates', 'exp_painting')
    op.drop_column('candidates', 'exp_line_leader')
    op.drop_column('candidates', 'exp_casting')
    op.drop_column('candidates', 'exp_food_processing')
    op.drop_column('candidates', 'exp_electronic_inspection')
    op.drop_column('candidates', 'exp_car_inspection')
    op.drop_column('candidates', 'exp_car_line')
    op.drop_column('candidates', 'exp_car_assembly')
    op.drop_column('candidates', 'exp_welding')
    op.drop_column('candidates', 'exp_packing')
    op.drop_column('candidates', 'exp_forklift')
    op.drop_column('candidates', 'exp_press')
    op.drop_column('candidates', 'exp_lathe')
    op.drop_column('candidates', 'exp_nc_lathe')
    op.drop_column('candidates', 'work_history_exit_company_7')
    op.drop_column('candidates', 'work_history_entry_company_7')
    op.drop_column('candidates', 'work_history_company_7')
    op.drop_column('candidates', 'family_separate_address_5')
    op.drop_column('candidates', 'family_residence_5')
    op.drop_column('candidates', 'family_age_5')
    op.drop_column('candidates', 'family_relation_5')
    op.drop_column('candidates', 'family_name_5')
    op.drop_column('candidates', 'family_separate_address_4')
    op.drop_column('candidates', 'family_residence_4')
    op.drop_column('candidates', 'family_age_4')
    op.drop_column('candidates', 'family_relation_4')
    op.drop_column('candidates', 'family_name_4')
    op.drop_column('candidates', 'family_separate_address_3')
    op.drop_column('candidates', 'family_residence_3')
    op.drop_column('candidates', 'family_age_3')
    op.drop_column('candidates', 'family_relation_3')
    op.drop_column('candidates', 'family_name_3')
    op.drop_column('candidates', 'family_separate_address_2')
    op.drop_column('candidates', 'family_residence_2')
    op.drop_column('candidates', 'family_age_2')
    op.drop_column('candidates', 'family_relation_2')
    op.drop_column('candidates', 'family_name_2')
    op.drop_column('candidates', 'family_separate_address_1')
    op.drop_column('candidates', 'family_residence_1')
    op.drop_column('candidates', 'family_age_1')
    op.drop_column('candidates', 'family_relation_1')
    op.drop_column('candidates', 'family_name_1')
    op.drop_column('candidates', 'gas_welding')
    op.drop_column('candidates', 'mobile_crane_over_5t')
    op.drop_column('candidates', 'mobile_crane_under_5t')
    op.drop_column('candidates', 'tama_kake')
    op.drop_column('candidates', 'forklift_license')
    op.drop_column('candidates', 'voluntary_insurance')
    op.drop_column('candidates', 'car_ownership')
    op.drop_column('candidates', 'license_expiry')
    op.drop_column('candidates', 'license_number')
    op.drop_column('candidates', 'residence_expiry')
    op.drop_column('candidates', 'residence_status')
    op.drop_column('candidates', 'passport_expiry')
    op.drop_column('candidates', 'passport_number')
    op.drop_column('candidates', 'registered_address')
    op.drop_column('candidates', 'building_name')
    op.drop_column('candidates', 'address_building')
    op.drop_column('candidates', 'address_banchi')
    op.drop_column('candidates', 'current_address')
    op.drop_column('candidates', 'hire_date')
    op.drop_column('candidates', 'marital_status')
