apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
    uid: prometheus
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
      serviceMap:
        datasourceUid: prometheus
