name: Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  backend:
    name: Backend lint & tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Static analysis
        run: python -m compileall app

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: pytest --maxfail=1 --disable-warnings -q

  frontend:
    name: Frontend lint, type-check & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-nextjs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend-nextjs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint -- --max-warnings=0

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build
